name: Build & Deploy WAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # or 'zulu'
          java-version: '8'

      - name: Build WAR with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download built WAR
        uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: Rsync WAR to Test Server
        uses: burnett01/rsync-deployments@7.1.0
        with:
          remote_host: ${{ secrets.TEST_SERVER_HOST }}
          remote_user: ${{ secrets.TEST_SERVER_USERNAME }}
          remote_key: ${{ secrets.TEST_SERVER_KEY }}
          path: HealthNutrition.war
          remote_path: /tmp/

      - name: Install WAR on Test Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          key: ${{ secrets.TEST_SERVER_KEY }}
          script: /root/tomcat/HealthNutrition/deploy.sh
